name: lavie
description: "A camera OTG app with screen sharing capabilities."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  camera: ^0.11.0
  carousel_slider: ^5.0.0
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  auto_route: ^9.2.2
  logging: ^1.2.0
  dio: ^5.7.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  scrollable_positioned_list: ^0.3.8
  flutter_typeahead: ^5.1.0
  flutter_painter_v2: ^2.0.1
  # Firebase dependencies
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  # WebRTC for screen sharing
  flutter_webrtc: ^0.9.47
  # Vibration for remote control
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.0
  auto_route_generator: ^9.0.0

dependency_overrides:
  # Note: override this plugin in order to fix the flipped camera preview issue
  # that happens from 0.6.6 to 0.6.10+3 on the time of writing.
  # https://github.com/flutter/flutter/issues/154241
  camera_android_camerax: 0.6.5+6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/lavie_logo.png"
