name: kyoryo
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  photo_view: ^0.14.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/tsunagu.png"
