// File generated by FlutterFire CLI.
// Contains Firebase configuration options for the app.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyPtD6BVEbefBieILYeBjLCS35abN7aM',
    appId: '1:631172388937:web:3de000ee30131caeba4798',
    messagingSenderId: '631172388937',
    projectId: 'lavie-196cd',
    authDomain: 'lavie-196cd.firebaseapp.com',
    storageBucket: 'lavie-196cd.firebasestorage.app',
    measurementId: 'G-HVM047V56C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbyPtD6BVEbefBieILYeBjLCS35abN7aM',
    appId: '1:631172388937:android:3de000ee30131caeba4798',
    messagingSenderId: '631172388937',
    projectId: 'lavie-196cd',
    storageBucket: 'lavie-196cd.firebasestorage.app',
  );
}
