// File generated by FlutterFire CLI.
// Contains Firebase configuration options for the app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLavie123456789WebApiKey',
    appId: '1:123456789012:web:abc123def456ghi789',
    messagingSenderId: '123456789012',
    projectId: 'lavie-app',
    authDomain: 'lavie-app.firebaseapp.com',
    storageBucket: 'lavie-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLavie123456789AndroidApiKey',
    appId: '1:123456789012:android:abc123def456ghi789',
    messagingSenderId: '123456789012',
    projectId: 'lavie-app',
    storageBucket: 'lavie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLavie123456789iOSApiKey',
    appId: '1:123456789012:ios:abc123def456ghi789',
    messagingSenderId: '123456789012',
    projectId: 'lavie-app',
    storageBucket: 'lavie-app.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.lavie.app',
  );
}
