name: Build Android with STG API

on:
  workflow_dispatch:

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build-android.yml
    with:
      ref: ${{ github.event.inputs.ref }}
      build_env: stg
    secrets:
      apiURL: ${{ secrets.API_URL_STG }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}