name: Build Android

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        default: "main"
        type: string
      build_env:
        required: true
        type: string
    secrets:
      apiURL:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AUTH0_DOMAIN:
        required: true
      AUTH0_CLIENT_ID:
        required: true
      AUTH0_AUDIENCE:
        required: true
      KEY_JKS:
        required: true
      ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      ANDROID_STORE_PASSWORD:
        required: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Determine ref
        id: get-ref
        run: |
          echo "ref=${{ inputs.ref }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11.0.21+9"
          cache: "gradle"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.4"
          cache: true

      - name: Create the Keystore
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo $KEY_JKS | base64 -d > android/key.jks

      - name: Get Packages
        run: flutter pub get

      - name: Generate .env file
        run: |
          TIMESTAMP=$(git show -s --format=%ct HEAD)
          echo "API_URL=${{ secrets.apiURL }}" > .env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
          echo "CURRENT_VERSION=$TIMESTAMP" >> .env
          echo "BUILD_ENV=${{ inputs.build_env }}" >> .env

      - name: Build Android App Bundle
        env:
          ALIAS: ${{ secrets.ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: |
          flutter build apk --release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: |
          FILE_LIST=$(ls build/app/outputs/flutter-apk/*.apk)
          echo "$FILE_LIST"
          TIMESTAMP=$(git show -s --format=%ct HEAD)
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://tsunagu-apk/${{ inputs.build_env }}/$TIMESTAMP.apk
