name: Build Android

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        default: 'main'
        type: string
    secrets:
      apiURL:
        required: true


jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Determine ref
        id: get-ref
        run: |
          echo "ref=${{ inputs.ref }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11.0.21+9"
          cache: "gradle"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.22.0"
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Generate .env file
        run: |
          echo "API_URL=${{ secrets.apiURL }}" > .env

      - name: Build Android App Bundle
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk