name: Build Android

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        default: 'main'
        type: string
      build_env:
        required: true
        type: string
    secrets:
      apiURL:
        required: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Determine ref
        id: get-ref
        run: |
          echo "ref=${{ inputs.ref }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11.0.21+9"
          cache: "gradle"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.4"
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Generate .env file
        run: |
          TIMESTAMP=$(date -d "${{ github.event.workflow_run.head_commit.timestamp }}" +%s)

          echo "API_URL=${{ secrets.apiURL }}" > .env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
          echo "CURRENT_VERSION=$TIMESTAMP" >> .env
          echo "BUILD_ENV=${{ inputs.build_env }}" >> .env

      - name: Build Android App Bundle
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: |
          FILE_LIST=$(ls build/app/outputs/flutter-apk/*.apk)
          echo "$FILE_LIST"
          TIMESTAMP=$(date -d "${{ github.event.workflow_run.head_commit.timestamp }}" +%s)
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://tsunagu-apk/${{ inputs.build_env }}/$TIMESTAMP.apk
