name: Build Android with DEV API

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build-android.yml
    with:
      ref: ${{ github.event.inputs.ref }}
      build_env: dev
    secrets:
      apiURL: ${{ secrets.API_URL_DEV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}