name: Build Android

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
  pull_request:
  push:
    branches: [main]

jobs:
    build:
        runs-on: macos-14
        steps:
          - name: Determine ref
            id: get-ref
            run: |
              input_ref="${{ inputs.ref }}"
              github_ref="${{ github.sha }}"
              ref="${input_ref:-$github_ref}"
              echo "ref=$ref" >> $GITHUB_OUTPUT

          - uses: actions/checkout@v4
            with:
              ref: ${{ steps.get-ref.outputs.ref }}

          - uses: actions/setup-java@v4
            with:
              distribution: "zulu"
              java-version: "11.0.21+9"
              cache: "gradle"

          - name: Setup Flutter SDK
            uses: subosito/flutter-action@v2
            with:
              channel: "stable"
              flutter-version: "3.16.9"
              cache: true

          - name: Get Packages
            run: flutter pub get

          - name: Generate .env file
            run: |
              echo "API_URL=${{ secrets.API_URL }}" > .env
      
          - name: Build Android App Bundle
            run: |
              flutter pub run flutter_launcher_icons:main
              flutter build apk --release
              flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64
      
          - name: Publish Android Artifact
            uses: actions/upload-artifact@v4
            with:
              name: release-apk
              path: build/app/outputs/flutter-apk/*.apk