name: Build Android

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        default: 'main'
        type: string
    secrets:
      apiURL:
        required: true
      BUILD_ENV:
        required: true

env:
  CURRENT_VERSION=$(date +%s)

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Determine ref
        id: get-ref
        run: |
          echo "ref=${{ inputs.ref }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11.0.21+9"
          cache: "gradle"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.4"
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Generate .env file
        run: |
          echo "API_URL=${{ secrets.apiURL }}" > .env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
          echo "CURRENT_VERSION=${{ env.CURRENT_VERSION }}" >> .env
          echo "BUILD_ENV=${{ secrets.BUILD_ENV }}" >> .env

      - name: Build Android App Bundle
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: |
          FILE_LIST=$(ls build/app/outputs/flutter-apk/*.apk)
          echo "$FILE_LIST"
          if [[ ${{ github.event_name }} == 'workflow_call' ]]; then
            PARENT_WORKFLOW=$(echo ${{ github.event.workflow_call.name }})
            if [[ $PARENT_WORKFLOW == 'build-android-dev' ]]; then
              S3_PATH='s3://tsunagu-apk/dev'
            elif [[ $PARENT_WORKFLOW == 'build-android-stg' ]]; then
              S3_PATH='s3://tsunagu-apk/stg'
            else
              echo "Unknown parent workflow: $PARENT_WORKFLOW"
              exit 1
            fi
            aws s3 cp build/app/outputs/flutter-apk/app-release.apk "$S3_PATH/${{ env.CURRENT_VERSION }}.apk"
          else
            echo "This workflow should be called by another workflow."
            exit 1
          fi