name: Build Android with STG API

on:
  workflow_dispatch:

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build-android.yml
    with:
      ref: ${{ github.event.inputs.ref }}
      build_env: stg
    secrets:
      apiURL: ${{ secrets.API_URL_STG }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      KEY_JKS: ${{ secrets.KEY_JKS }}
      ALIAS: ${{ secrets.ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}